services:
  db:
    image: postgres:15-alpine
    container_name: agenda-db
    restart: always
    environment:
      POSTGRES_USER: user_agenda
      POSTGRES_PASSWORD: password_agenda
      POSTGRES_DB: agenda_db
    ports:
      - "5432:5432"
    volumes:
      - agenda_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_agenda -d agenda_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      target: runner
    container_name: agenda-api
    restart: always
    environment:
      DATABASE_URL: "postgresql://user_agenda:password_agenda@db:5432/agenda_db?schema=public"
      JWT_SECRET: "tu_secreto_super_seguro"
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy --schema=apps/api/prisma/schema.prisma && node apps/api/dist/main.js"
    ports:
      - "3001:3001"

  web:
    build:
      context: .
      target: runner
    container_name: agenda-web
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: "http://tu-ip-o-dominio:3001"
      PORT: 3000
    depends_on:
      - api
    command: npm start --workspace=web
    ports:
      - "3000:3000"

volumes:
  agenda_db_data:
